import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className='bg-sky-600 px-5 py-3 flex gap-5 justify-center'>
          <Link href={'/'}>Home</Link>
          <Link href={'/todo'}>Todo App</Link>
          <Link href={'contact-us'}>Contact Us</Link>
        </header>

        {children}

        <footer>
        <p> &copy; PIAIC219867 All Rights Reserved </p>
        </footer>
        </body>
    </html>
  )
}
